### ISSUE TITLE
Fladle not setting GOOGLE_APPLICATION_CREDENTIALS and GOOGLE_CLOUD_PROJECT env vars

### ISSUE THREAD

**Issue by tir38** [runningcode/fladle#16]
It's been a few weeks since I ran Fladle on my local machine. It was working fine before. Today I get two errors. First one:

```
> Task :app:execFlank FAILED
project is not set. Define GOOGLE_CLOUD_PROJECT or set project in flank.yml
 See https://github.com/GoogleCloudPlatform/google-cloud-java#specifying-a-project-id
```

So I then manually set  `projectId` in build.gradle and run again. I then get this error:

```
Caused by: java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value 'null': File does not exist.
```

So I think Fladle is not correctly setting `GOOGLE_APPLICATION_CREDENTIALS` and `GOOGLE_CLOUD_PROJECT`  env vars (https://github.com/TestArmada/flank#authenticate-with-a-service-account)

I don't really think I changed anything. I'm still using v 0.2.12 of this plugin and using the default version of Flank (3.1.1).

**Comment by bootstraponline** [comment]
flank should be auto detecting the credentials and project directly from the service account JSON

seems like fladle may not be passing that info along.

**Comment by bootstraponline** [comment]
If there are changes that can be made upstream in flank to better support fladle let me know.

**Comment by tir38** [comment]
project level build.gradle:

```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" } // for Fladle
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0-beta01'
        classpath "gradle.plugin.com.osacky.flank.gradle:fladle:0.2.12"
        ....
    }
}
```

important parts of app build.gradle:

```
apply plugin: 'com.android.application'
apply plugin: "com.osacky.fladle"
...

import com.osacky.flank.gradle.Device

fladle {
    serviceAccountCredentials("${project.file("firebase-test-lab-service-account.json")}")
    useOrchestrator = true
    testShards = 2
    devices = [
            new Device("Nexus5X", 25, null, null)
    ]
}

android {
    compileSdkVersion 28
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28

    }
    ...
}
```

resulting flank.yml

```
gcloud:
  app: /Users/example/app/build/outputs/apk/debug/app-debug.apk
  test: /Users/example/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  use-orchestrator: true
  auto-google-login: false
# projectId will be automatically discovered
  device:
  - model: Nexus5X
    version: 25


flank:
  testShards: 2
```

I can't figure out how to get `flank` command running so I can't run flank doctor.
