### ISSUE TITLE
Yaml formatting error with projectId

### ISSUE THREAD

**Issue by tasomaniac** [runningcode/fladle#253]
Hi, we came across a very weird error while using fladle on a new project. Our project id on Firebase has dash `-` in it. And this creates an issue parsing the configuration since dash is a reserved char. According to my google search,  this actually depends on yaml parser.

I was thinking of creating a PR but I was not sure what is the best way to handle this. Should we just wrap the value into quotes?

```yaml
# instead of this
  projectId: some-funny-name

# this
  projectId: "some-funny-name"
```

Here is the error I receive:

```
> Task :app:execFlankCriticalPath
version: v21.03.1
revision: **redacted**
session id: **redacted**

Invalid value for [project]: no argument value found
```

**Comment by runningcode** [comment]
@tasomaniac would you be able to paste the error you are seeing here?

@bootstraponline would this help? Can flank parse a project with a `-` in it?

**Comment by tasomaniac** [comment]
Sorry, I cannot believe I forgot :) It was on my clipboard. I will update above.

**Comment by bootstraponline** [comment]
`project: flank-open-source` is what we use on flank. We can parse projects with `-`.

I think the key should be `project` not  `projectId` in the yaml. Maybe fladle exposes this as `projectId`?

@pawelpasterz Do you have additional context?

**Comment by runningcode** [comment]
@tasomaniac what version of flank and fladle are you using?

**Comment by runningcode** [comment]
@tasomaniac can you also explain how you are specifying the project id in the fladle configuration block?

Can you also let us know if you are using a service account or user authentication?

**Comment by tasomaniac** [comment]
Service account works fine. I wanted to use the service account only on the CI. And developers in the team can use `flankAuth` to setup locally. Not sure if it makes a difference but we also have numbers in the id.

I will try to run the generated yaml with flank directly. Let's see 🤞 

We just tried the following config

```
fladle {
  projectId.set("some-project-12345")
} 
```

**Comment by tasomaniac** [comment]
Yes, I can reproduce it by running manually via `flank.jar`. Unfortunately putting single or double quotes does not help.

**Comment by tasomaniac** [comment]
Here is my yaml file. I guess this should be an issue on Flank actually. I was just wondering if there could be a way to workaround here.


```
gcloud:
  app: /path/app/build/outputs/apk/debug/app-debug.apk
  test: /path/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  device:
  - model: Pixel2
    version: 28

  use-orchestrator: true
  auto-google-login: false
  record-video: true
  performance-metrics: true
  timeout: 15m

flank:
  max-test-shards: 10
  project: some-project-54934
  keep-file-path: false
  ignore-failed-tests: false
  disable-sharding: false
  smart-flank-disable-upload: false
  legacy-junit-result: false
  full-junit-result: false
  output-style: single
```
