### ISSUE TITLE
Missing environment-variables 

### ISSUE THREAD

**Issue by eric-labelle** [runningcode/fladle#432]
There is a discrepancy between `runFlank` and `printYml` commands. 

Executing `./gradlew printYaml` would print the 
```
gcloud:
...
 device:
 - model: Pixel2.arm
   version: 26
 use-orchestrator: true
 auto-google-login: false
 record-video: true
 performance-metrics: false
 timeout: 15m
 environment-variables:
   failureScreenshots: true
   clearPackageData: true
 test-targets:
 - annotation com.example.MyTests
 directories-to-pull:
 - /sdcard/com.example.debug/
 num-flaky-test-attempts: 1
```

when executing `./gradlew runFlank` the `environment-variables` is missing
```
gcloud:

...

 record-video: true
 timeout: 15m
 async: false
 network-profile: null
 results-history-name: null
 additional-apks:
 auto-google-login: false
 use-orchestrator: true
 directories-to-pull:
   - /sdcard/com.example.debug/
 grant-permissions: all
 type: null
 other-files:
 scenario-numbers:
 scenario-labels:
 obb-files:
 obb-names:
 performance-metrics: false
 num-uniform-shards: null
 test-runner-class: null
 test-targets:
   - annotation com.example.MyTests
 robo-directives:
 robo-script: null
 device:
   - model: Pixel2.arm
     version: 26
     locale: en
     orientation: portrait
 num-flaky-test-attempts: 1
 test-targets-for-shard:
 fail-fast: false
  parameterized-tests: default
```

Makes it very hard to debug issues without this property printed. Not sure if the issue is with fladle or flank though?
